[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "holidata"
version = "2026.9.0"
description = "Holidata is a utility for algorithmically producing holidays for a given locale and year"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11, <4"
authors = [
    { name = "Gothenburg Bit Factory", email = "support@gothenburgbitfactory.org" },
]
keywords = ["holiday", "calendar"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "arrow >= 1.4.0",
    "docopt >= 0.6.2",
]

[project.urls]
"Bug Reports" = "https://github.com/GothenburgBitFactory/holidata/issues"
Source = "https://github.com/GothenburgBitFactory/holidata"
Website = "https://holidata.net"

[project.scripts]
holidata = "holidata.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
lint.select = ["E", "F", "W", "I"]
lint.ignore = ["E501"]

# Ignore F403 ('from module import *' used)
lint.per-file-ignores."src/holidata/holidays/__init__.py" = ["F403"]
lint.per-file-ignores."src/holidata/__init__.py" = ["F403"]

[dependency-groups]
dev = [
    "mypy >= 2.3.1",
    "pytest >= 9.0.2",
    "ruff >= 0.16.8",
    "syrupy >= 6.1.1",
    "types-docopt >= 0.6.11.20241107",
    "types-python-dateutil >= 2.9.0.20260807",
]
